# robot_weights.yaml - backflip
simple_humanoid:
  ready_base_pos: [0.0, 100.0, 0.0]
  ready_base_rot: [100.0, 0.0, 100.0]
  ready_joint: [50.0]
  ready_base_v: [25.0, 100.0, 0.0]
  ready_base_w: [100.0, 0.0, 100.0]
  ready_joint_v: [1.0]
  
  ready_terminal_base_pos: [25.0, 100.0, 0.0]
  ready_terminal_base_rot: [100.0, 0.0, 100.0]
  ready_terminal_joint: [75.0]
  ready_terminal_base_v: [0.0, 100.0, 0.0]
  ready_terminal_base_w: [100.0, 0.0, 100.0]
  ready_terminal_joint_v: [0.0]

  takeoff_base_pos: [25.0, 100.0, 0.0]
  takeoff_base_rot: [100.0, 0.0, 100.0]
  takeoff_joint: [50.0]
  takeoff_base_v: [25.0, 100.0, 10.0]
  takeoff_base_w: [100.0, 0.0, 100.0]
  takeoff_joint_v: [0.0]
  
  takeoff_terminal_base_pos: [25.0, 100.0, 100.0]
  takeoff_terminal_base_rot: [100.0, 0.0, 100.0]
  takeoff_terminal_joint: [50.0]
  takeoff_terminal_base_v: [0.0, 0.0, 200.0]
  takeoff_terminal_base_w: [100.0, 0.0, 100.0]
  takeoff_terminal_joint_v: [0.0] 
  
  flyup_base_pos: [10.0, 100.0, 0.0]
  flyup_base_rot: [100.0, 10.0, 100.0]
  flyup_joint: [75.0]
  flyup_base_v: [0.0, 100.0, 0.0]
  flyup_base_w: [100.0, 100.0, 100.0]
  flyup_joint_v: [0.5]
  
  flyup_terminal_base_pos: [1.0, 100.0, 0.0]
  flyup_terminal_base_rot: [100.0, 100.0, 100.0]
  flyup_terminal_joint: [100.0]
  flyup_terminal_base_v: [0.0, 100.0, 50.0]
  flyup_terminal_base_w: [100.0, 100.0, 100.0]
  flyup_terminal_joint_v: [0.0] 

  flydown_base_pos: [30.0, 0.0, 0.0]
  flydown_base_rot: [10.0, 10.0, 10.0]
  flydown_joint: [120.0]
  flydown_base_v: [0.0, 0.0, 0.0]
  flydown_base_w: [0.0, 0.0, 0.0]
  flydown_joint_v: [0.1]
  
  flydown_terminal_base_pos: [80.0, 0.0, 100.0]
  flydown_terminal_base_rot: [10.0, 10.0, 10.0]
  flydown_terminal_joint: [120.0]
  flydown_terminal_base_v: [0.0, 0.0, 0.0]
  flydown_terminal_base_w: [0.0, 0.0, 0.0]
  flydown_terminal_joint_v: [0.0] 

  landing_base_pos: [0.0, 0.0, 0.0]
  landing_base_rot: [10.0, 10.0, 10.0]
  landing_joint: [120.0]
  landing_base_v: [0.0, 0.0, 0.0]
  landing_base_w: [0.0, 0.0, 0.0]
  landing_joint_v: [0.0]
  
  landed_terminal_base_pos: [150.0, 10.0, 150.0]
  landed_terminal_base_rot: [50.0, 50.0, 50.0]
  landed_terminal_joint: [100.0]
  landed_terminal_base_v: [0.0, 0.0, 0.0]
  landed_terminal_base_w: [0.0, 0.0, 0.0]
  landed_terminal_joint_v: [6.0]

  side_takeoff_base_pos: [10.0, 10.0, 10.0]
  side_takeoff_base_rot: [50.0, 10.0, 50.0]
  side_takeoff_joint: [100.0]
  side_takeoff_base_v: [25.0, 100.0, 500.0]  
  side_takeoff_base_w: [50.0, 10.0, 50.0]
  side_takeoff_joint_v: [1.0]

  side_takeoff_terminal_base_pos: [50.0, 50.0, 100.0]
  side_takeoff_terminal_base_rot: [200.0, 10.0, 100.0]
  side_takeoff_terminal_joint: [50.0]
  side_takeoff_terminal_base_v: [10.0, 10.0, 1000.0] 
  side_takeoff_terminal_base_w: [800.0, 10.0, 100.0]
  side_takeoff_terminal_joint_v: [1.0] 


  side_flyup_base_pos: [10.0, 10.0, 10.0]
  side_flyup_base_rot: [800.0, 500.0, 500.0]
  side_flyup_joint: [10.0]
  side_flyup_base_v: [0.0, 0.0, 0.0]
  side_flyup_base_w: [500.0, 5.0, 5.0]
  side_flyup_joint_v: [0.1]

  side_flyup_terminal_base_pos: [50.0, 50.0, 100.0]
  side_flyup_terminal_base_rot: [1000.0, 100.0, 100.0]
  side_flyup_terminal_joint: [50.0]
  side_flyup_terminal_base_v: [10.0, 10.0, 100.0]
  side_flyup_terminal_base_w: [500.0, 100.0, 100.0]
  side_flyup_terminal_joint_v: [0.0] 

  side_flydown_base_pos: [5.0, 50.0, 5.0]
  side_flydown_base_rot: [5.0, 5.0, 5.0]
  side_flydown_joint: [20.0]
  side_flydown_base_v: [0.0, 0.0, 0.0]
  side_flydown_base_w: [500.0, 3.0, 3.0]
  side_flydown_joint_v: [0]

  side_flydown_terminal_base_pos: [1000.0, 1000.0, 1100.0]
  side_flydown_terminal_base_rot: [200.0, 100.0, 100.0] 
  side_flydown_terminal_joint: [150.0]
  side_flydown_terminal_base_v: [1.0, 1.0, 1.0]
  side_flydown_terminal_base_w: [1.0, 1.0, 1.0]
  side_flydown_terminal_joint_v: [0.1]

  side_landing_base_pos: [500.0, 500.0, 800.0]
  side_landing_base_rot: [800.0, 500.0, 500.0]
  side_landing_joint: [150.0]                   
  side_landing_base_v: [10.0, 10.0, 10.0]         
  side_landing_base_w: [10.0, 10.0, 10.0]  
  side_landing_joint_v: [10.0]

  side_landed_base_pos: [500.0, 500.0, 500.0]
  side_landed_base_rot: [1000.0, 1000.0, 1000.0]
  side_landed_joint: [170.0]                   
  side_landed_base_v: [50.0, 50.0, 50.0]
  side_landed_base_w: [50.0, 50.0, 50.0]       
  side_landed_joint_v: [10.0]

tocabi:
  ready_base_pos: [0.0, 100.0, 0.0]
  ready_base_rot: [100.0, 0.0, 100.0]
  ready_joint: [50.0]
  ready_base_v: [25.0, 100.0, 0.0]
  ready_base_w: [100.0, 0.0, 100.0]
  ready_joint_v: [1.0]
  
  ready_terminal_base_pos: [25.0, 100.0, 0.0]
  ready_terminal_base_rot: [100.0, 0.0, 100.0]
  ready_terminal_joint: [75.0]
  ready_terminal_base_v: [0.0, 100.0, 0.0]
  ready_terminal_base_w: [100.0, 0.0, 100.0]
  ready_terminal_joint_v: [0.0]

  takeoff_base_pos: [25.0, 100.0, 0.0]
  takeoff_base_rot: [100.0, 0.0, 100.0]
  takeoff_joint: [50.0]
  takeoff_base_v: [25.0, 100.0, 10.0]
  takeoff_base_w: [100.0, 0.0, 100.0]
  takeoff_joint_v: [0.0]
  
  takeoff_terminal_base_pos: [25.0, 100.0, 100.0]
  takeoff_terminal_base_rot: [100.0, 0.0, 100.0]
  takeoff_terminal_joint: [50.0]
  takeoff_terminal_base_v: [0.0, 0.0, 200.0]
  takeoff_terminal_base_w: [100.0, 0.0, 100.0]
  takeoff_terminal_joint_v: [0.0] 
  
  flyup_base_pos: [0.0, 100.0, 0.0]
  flyup_base_rot: [100.0, 10.0, 100.0]
  flyup_joint: [75.0]
  flyup_base_v: [0.0, 100.0, 0.0]
  flyup_base_w: [100.0, 100.0, 100.0]
  flyup_joint_v: [0.5]
  
  flyup_terminal_base_pos: [0.0, 100.0, 50.0]
  flyup_terminal_base_rot: [100.0, 100.0, 100.0]
  flyup_terminal_joint: [100.0]
  flyup_terminal_base_v: [0.0, 100.0, 50.0]
  flyup_terminal_base_w: [100.0, 100.0, 100.0]
  flyup_terminal_joint_v: [0.0] 

  flydown_base_pos: [0.0, 0.0, 0.0]
  flydown_base_rot: [10.0, 10.0, 10.0]
  flydown_joint: [120.0]
  flydown_base_v: [0.0, 0.0, 0.0]
  flydown_base_w: [0.0, 0.0, 0.0]
  flydown_joint_v: [0.1]
  
  flydown_terminal_base_pos: [0.0, 0.0, 80.0]
  flydown_terminal_base_rot: [10.0, 10.0, 10.0]
  flydown_terminal_joint: [120.0]
  flydown_terminal_base_v: [0.0, 0.0, 0.0]
  flydown_terminal_base_w: [0.0, 0.0, 0.0]
  flydown_terminal_joint_v: [0.0] 

  landing_base_pos: [0.0, 0.0, 0.0]
  landing_base_rot: [10.0, 10.0, 10.0]
  landing_joint: [120.0]
  landing_base_v: [0.0, 0.0, 0.0]
  landing_base_w: [0.0, 0.0, 0.0]
  landing_joint_v: [0.0]
  
  landed_terminal_base_pos: [120.0, 120.0, 120.0]
  landed_terminal_base_rot: [50.0, 50.0, 50.0]
  landed_terminal_joint: [100.0]
  landed_terminal_base_v: [0.0, 0.0, 0.0]
  landed_terminal_base_w: [0.0, 0.0, 0.0]
  landed_terminal_joint_v: [5.0]

  side_takeoff_base_pos: [25.0, 100.0, 0.0]
  side_takeoff_base_rot: [100.0, 0.0, 100.0]
  side_takeoff_joint: [50.0]
  side_takeoff_base_v: [25.0, 100.0, 10.0]
  side_takeoff_base_w: [100.0, 0.0, 100.0]
  side_takeoff_joint_v: [0.0]
  
  side_takeoff_terminal_base_pos: [25.0, 100.0, 100.0]
  side_takeoff_terminal_base_rot: [100.0, 0.0, 100.0]
  side_takeoff_terminal_joint: [50.0]
  side_takeoff_terminal_base_v: [0.0, 0.0, 200.0]
  side_takeoff_terminal_base_w: [100.0, 0.0, 100.0]
  side_takeoff_terminal_joint_v: [0.0] 
  
  side_flyup_base_pos: [10.0, 90.0, 10.0]
  side_flyup_base_rot: [100.0, 10.0, 100.0]
  side_flyup_joint: [75.0]
  side_flyup_base_v: [0.0, 100.0, 0.0]
  side_flyup_base_w: [100.0, 100.0, 100.0]
  side_lyup_joint_v: [0.5]
  
  side_flyup_terminal_base_pos: [5.0, 100.0, 50.0]
  side_flyup_terminal_base_rot: [100.0, 100.0, 100.0]
  side_flyup_terminal_joint: [100.0]
  side_flyup_terminal_base_v: [0.0, 100.0, 50.0]
  side_flyup_terminal_base_w: [100.0, 100.0, 100.0]
  side_flyup_terminal_joint_v: [0.0] 

  side_lydown_base_pos: [8.0, 8.0, 25.0]
  side_flydown_base_rot: [30.0, 10.0, 10.0]
  side_flydown_joint: [120.0]
  side_flydown_base_v: [0.0, 0.0, 0.0]
  side_flydown_base_w: [0.0, 0.0, 0.0]
  side_flydown_joint_v: [0.1]
  
  side_flydown_terminal_base_pos: [30.0, 30.0, 50.0]
  side_flydown_terminal_base_rot: [20.0, 10.0, 10.0]
  side_flydown_terminal_joint: [110.0]
  side_flydown_terminal_base_v: [0.0, 0.0, 0.0]
  side_flydown_terminal_base_w: [0.0, 0.0, 0.0]
  side_flydown_terminal_joint_v: [0.0] 

  side_landing_base_pos: [0.0, 0.0, 0.0]
  side_landing_base_rot: [20.0, 10.0, 10.0]
  side_landing_joint: [120.0]
  side_landing_base_v: [0.0, 0.0, 0.0]
  side_landing_base_w: [0.0, 0.0, 0.0]
  side_landing_joint_v: [0.0]
  
  side_landed_terminal_base_pos: [140.0, 140.0, 150.0]
  side_landed_terminal_base_rot: [60.0, 50.0, 50.0]
  side_landed_terminal_joint: [100.0]
  side_landed_terminal_base_v: [0.0, 0.0, 0.0]
  side_landed_terminal_base_w: [0.0, 0.0, 0.0]
  side_landed_terminal_joint_v: [5.0]


p73:
  ready_base_pos: [0.0, 100.0, 0.0]
  ready_base_rot: [100.0, 0.0, 100.0]
  ready_joint: [50.0]
  ready_base_v: [25.0, 100.0, 0.0]
  ready_base_w: [100.0, 0.0, 100.0]
  ready_joint_v: [1.0]
  
  ready_terminal_base_pos: [25.0, 100.0, 0.0]
  ready_terminal_base_rot: [100.0, 0.0, 100.0]
  ready_terminal_joint: [75.0]
  ready_terminal_base_v: [0.0, 100.0, 0.0]
  ready_terminal_base_w: [100.0, 0.0, 100.0]
  ready_terminal_joint_v: [0.0]

  takeoff_base_pos: [25.0, 100.0, 0.0]
  takeoff_base_rot: [100.0, 0.0, 100.0]
  takeoff_joint: [50.0]
  takeoff_base_v: [25.0, 100.0, 10.0]
  takeoff_base_w: [100.0, 0.0, 100.0]
  takeoff_joint_v: [0.0]
  
  takeoff_terminal_base_pos: [25.0, 100.0, 100.0]
  takeoff_terminal_base_rot: [100.0, 0.0, 100.0]
  takeoff_terminal_joint: [50.0]
  takeoff_terminal_base_v: [0.0, 0.0, 200.0]
  takeoff_terminal_base_w: [100.0, 0.0, 100.0]
  takeoff_terminal_joint_v: [0.0] 
  
  flyup_base_pos: [10.0, 100.0, 0.0]
  flyup_base_rot: [100.0, 10.0, 100.0]
  flyup_joint: [75.0]
  flyup_base_v: [0.0, 100.0, 0.0]
  flyup_base_w: [100.0, 100.0, 100.0]
  flyup_joint_v: [0.5]
  
  flyup_terminal_base_pos: [10.0, 100.0, 10.0]
  flyup_terminal_base_rot: [100.0, 100.0, 100.0]
  flyup_terminal_joint: [120.0]
  flyup_terminal_base_v: [0.0, 100.0, 50.0]
  flyup_terminal_base_w: [100.0, 100.0, 100.0]
  flyup_terminal_joint_v: [0.0] 

  flydown_base_pos: [10.0, 0.0, 0.0]
  flydown_base_rot: [10.0, 10.0, 10.0]
  flydown_joint: [120.0]
  flydown_base_v: [0.0, 0.0, 0.0]
  flydown_base_w: [0.0, 0.0, 0.0]
  flydown_joint_v: [0.1]
  
  flydown_terminal_base_pos: [60.0, 0.0, 80.0]
  flydown_terminal_base_rot: [20.0, 20.0, 20.0]
  flydown_terminal_joint: [120.0]
  flydown_terminal_base_v: [0.0, 0.0, 0.0]
  flydown_terminal_base_w: [0.0, 0.0, 0.0]
  flydown_terminal_joint_v: [0.0] 

  landing_base_pos: [0.0, 0.0, 0.0]
  landing_base_rot: [10.0, 10.0, 10.0]
  landing_joint: [120.0]
  landing_base_v: [0.0, 0.0, 0.0]
  landing_base_w: [0.0, 0.0, 0.0]
  landing_joint_v: [0.0]
  
  landed_terminal_base_pos: [150.0, 150.0, 150.0]
  landed_terminal_base_rot: [50.0, 50.0, 50.0]
  landed_terminal_joint: [100.0]
  landed_terminal_base_v: [0.0, 0.0, 0.0]
  landed_terminal_base_w: [0.0, 0.0, 0.0]
  landed_terminal_joint_v: [6.0]

  side_takeoff_base_pos: [25.0, 100.0, 0.0]
  side_takeoff_base_rot: [100.0, 0.0, 100.0]
  side_takeoff_joint: [50.0]
  side_takeoff_base_v: [25.0, 100.0, 10.0]
  side_takeoff_base_w: [200.0, 0.0, 100.0]
  side_takeoff_joint_v: [0.0]
  
  side_takeoff_terminal_base_pos: [25.0, 100.0, 100.0]
  side_takeoff_terminal_base_rot: [100.0, 0.0, 100.0]
  side_takeoff_terminal_joint: [50.0]
  side_takeoff_terminal_base_v: [0.0, 0.0, 200.0]
  side_takeoff_terminal_base_w: [200.0, 0.0, 100.0]
  side_takeoff_terminal_joint_v: [0.0] 
  
  side_flyup_base_pos: [50.0, 90.0, 90.0]
  side_flyup_base_rot: [100.0, 10.0, 100.0]
  side_flyup_joint: [100.0]
  side_flyup_base_v: [50.0, 100.0, 0.0]
  side_flyup_base_w: [200.0, 100.0, 100.0]
  side_flyup_joint_v: [0.5]
  
  side_flyup_terminal_base_pos: [50.0, 100.0, 50.0]
  side_flyup_terminal_base_rot: [100.0, 50.0, 50.0]
  side_flyup_terminal_joint: [90.0]
  side_flyup_terminal_base_v: [0.0, 100.0, 50.0]
  side_flyup_terminal_base_w: [200.0, 100.0, 100.0]
  side_flyup_terminal_joint_v: [0.0] 

  side_flydown_base_pos: [8.0, 5.0, 20.0]
  side_flydown_base_rot: [60.0, 30.0, 30.0]
  side_flydown_joint: [90.0]
  side_flydown_base_v: [20.0, 100.0, 20.0]
  side_flydown_base_w: [200.0, 50.0, 50.0]
  side_flydown_joint_v: [0.1]
  
  side_flydown_terminal_base_pos: [30.0, 30.0, 50.0]
  side_flydown_terminal_base_rot: [90.0, 30.0, 30.0]
  side_flydown_terminal_joint: [110.0]
  side_flydown_terminal_base_v: [0.0, 0.0, 0.0]
  side_flydown_terminal_base_w: [100.0, 0.0, 0.0]
  side_flydown_terminal_joint_v: [0.0] 

  side_landing_base_pos: [0.0, 0.0, 0.0]
  side_landing_base_rot: [20.0, 10.0, 10.0]
  side_landing_joint: [120.0]
  side_landing_base_v: [0.0, 0.0, 0.0]
  side_landing_base_w: [0.0, 0.0, 0.0]
  side_landing_joint_v: [0.0]
  
  side_landed_terminal_base_pos: [140.0, 140.0, 150.0]
  side_landed_terminal_base_rot: [50.0, 50.0, 50.0]
  side_landed_terminal_joint: [100.0]
  side_landed_terminal_base_v: [0.0, 0.0, 0.0]
  side_landed_terminal_base_w: [0.0, 0.0, 0.0]
  side_landed_terminal_joint_v: [5.0]
